### PR TITLE
Package restructuring to prep for npm publish

### PR DESCRIPTION
**Pull request by ccostino**
This change set addresses a couple of issues with the initial work committed for this repository in an effort to get the package ready for publishing to npm.

cc @jeremiak and @mbland - I am trying to get this prepped and ready to go but I am still having problems using the module when importing it, e.g., opening the Node REPL in the shell and then trying to use the module.  I figured I would submit this PR now and get the ball rolling on some conversation about what else might need to be done to shore things up.  Thanks!

### CODE REVIEW

**Comment by jeremiak** [comment]
@ccostino made some changes, the tool now works from the node REPL and the tests are passing. Major API changes:
* The main class now uses our schema by default instead of requiring one to be passed in. It now expects JSON, if anything is given, so doesn't parse that

**Comment by ccostino** [comment]
@jeremiak, thank you!  I think the issue was just not passing in a schema with the constructor initially, but these updates take care of that.  :heart: the comments added too for the method definitions, thanks! :-)

**Comment by mbland** [comment]
This looks good, but my only question is with regards to how clients will actually instantiate the Validator class. I like the style from http://thenodeway.io/posts/designing-custom-types/ whereby importing the module amounts to importing the constructor, for example:

```js
var Validator = require('about-yml-validator');
var v = new Validator();
```

So in my mind the question is what do we call this package, and thus pass as the `require()` argument? It would seem `about-yml-validator` would be a good choice for the package as it is now. Otherwise, if we moved `index.js` back to `lib/validator.js`, I think `about-yml/validator` would work, correct?

Thoughts?

**Comment by ccostino** [comment]
With @jeremiak's change we're able to do exactly this now:

```
var Validator = require('about-yml-npm');
var v = new Validator();
```

Before I think it was just a matter of passing in a schema as an argument and I wasn't doing that, though initially I was running into a module import error.

I agree that we should probably reconsider the naming of the package, though.  `about-yml-validator` sounds good to me, though if we feel that there might be more functionality (and therefore more sub-modules, so-to-speak), then `about-yml/validator` probably makes more sense.

**Comment by jeremiak** [comment]
The best part about packaging it as `about-yml-validator` (with tests) is that if we want `about-yml` in the future, there is no reason that it can't simply list this module as a dependency and then export the functionality in a different way.

Also, to get it work with the `/` you'd want to have `validator.js` at the root of the project. `require()` takes the name and then just looks for that folder in various `node_modules` and then you just go into that further with normal POSIX path stuff. So if it was in lib you'd have to do something like `require("about-yml-validator/lib/validator")`.

**Comment by mbland** [comment]
Ahh, good to know, @jeremiak. Perhaps we should update the package name in this PR, too. (Though, as you and I discussed in an earlier meeting today, that makes things a little more complicated for `.about.yml` modeling. Oh, the irony. :smiley:)

**Comment by ccostino** [comment]
I'm all for getting this named appropriately in all the places it makes sense to now, before publishing.  I have to imagine it's even more complicated once that step is done!

**Comment by ccostino** [comment]
@jeremiak, I just spoke with @mbland about this some more and we're in agreement with your suggestions so we're going to move forward with `about-yml-validator`.

**Pull request merged**
